proto script to generate proto code and ci workflow to check for integrity

diff --git a/.github/workflows/ci-go.yml b/.github/workflows/ci-go.yml
--- a/.github/workflows/ci-go.yml
+++ b/.github/workflows/ci-go.yml
@@ -10,6 +10,7 @@ on:
       - ".github/**"
       - "**.go"
       - "**/config.yaml"
+      - "**/proto/**"
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -25,3 +26,33 @@ jobs:
         run: go vet ./...
       - name: Test
         run: go test ./...
+  check-proto-integrity:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
+        name: Checkout repository
+
+      - uses: actions/setup-go@v4
+        name: Set up Go
+        with:
+          go-version: "1.23"
+
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+      - name: Run Proto Generation
+        run: ./proto/gen_proto.sh
+
+      - name: Check for Uncommitted Changes
+        run: |
+          if [[ -n "$(git status --porcelain)" ]]; then
+            # Capture the list of uncommitted files
+            UNCOMMITTED_FILES=$(git status --porcelain)
+            echo "::error::Proto generation step has uncommitted changes: $UNCOMMITTED_FILES"
+            echo "Please run the following command locally and commit the results:"
+            echo "- \`./proto/gen_proto.sh\`"
+            exit 1
+          else
+            echo "Proto generation check passed. No uncommitted changes."
+          fi
